// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZjMUkKtV5Sh6YBmb8LGCOPaypGRJETGM',
    appId: '1:344267541233:web:0493d111c64f3562a2f750',
    messagingSenderId: '344267541233',
    projectId: 'best-farmer-africa',
    authDomain: 'best-farmer-africa.firebaseapp.com',
    storageBucket: 'best-farmer-africa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjxcRBBPKwSkWbrVN4cuymrcftHOOQC5A',
    appId: '1:344267541233:android:8dc6cfa96938ed69a2f750',
    messagingSenderId: '344267541233',
    projectId: 'best-farmer-africa',
    storageBucket: 'best-farmer-africa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB17vnFnpD5V58CpFBdw3wdNOT7uBpoHlg',
    appId: '1:344267541233:ios:dbc08216f6279c58a2f750',
    messagingSenderId: '344267541233',
    projectId: 'best-farmer-africa',
    storageBucket: 'best-farmer-africa.firebasestorage.app',
    iosBundleId: 'com.example.bfa',
  );
}
